name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      working-directory: ./app
      run: docker build . --file Dockerfile --tag jacarandastock_fontend:$(date +%s)
